### ISSUE TITLE
Add more DSA Question

### ISSUE THREAD

**Issue by Abhay0809** [Abhay0809/DSA-Series#1]

**Comment by Noobham** [comment]
hey Abhnay ,
Can you  please assign me this issue .. What should i do to resolve this issue

**Comment by Abhay0809** [comment]
Basically add more DSA based questions along with solution.

**Comment by karan-2028** [comment]
i want to contribute on this issuse.
 please assign me

**Comment by sumanchaurasiya** [comment]
I would like to contribute.

**Comment by namratanimmi** [comment]
I would like to contribute , please assign it to me.

**Comment by JASKIRAT11011** [comment]
I would like to contribute , please assign it to me.

**Comment by sanglap-02** [comment]
I would like to add some good dsa based questions along with answer with explanations in comment. please assign it to me

**Comment by AditiBendre** [comment]
Can i contribute to this issue?

**Comment by sumit402** [comment]
i would like to contribute, please assign it to me.
