### ISSUE TITLE
Add Binary Search

### ISSUE THREAD

**Issue by Saksham294** [Abhay0809/DSA-Series#11]
I think we should add binary search and some questions related to it

**Comment by sanglap-02** [comment]
hi I can write the code for binary search and I would love to contribute some good questions and solutions regarding binary search, such as 
1) search element in sorted and rotated array
2) Median of two sorted array 
3) koko eating bananas 
4) Allocate minimum number of pages 
5) Aggressive cows

So please assign this issue to me
