### ISSUE TITLE
Update Readme Section

### ISSUE THREAD

**Issue by Abhay0809** [Abhay0809/DSA-Series#2]

**Comment by Vani177** [comment]
hey, i can solve this issue, can you please assign this to me?

**Comment by Abhay0809** [comment]
okay

**Comment by karan-2028** [comment]
can you assign me

**Comment by Vani177** [comment]
> okay

hey, i wanted to say that should i also add a file for license.md as well? so as to add them in the readme.md file or do i exclude it?

**Comment by Abhay0809** [comment]
okay
